backend:
  name: github
  repo: afisch710/alexfischman.dev
  branch: development
  auth_scope: repo
  client_id: Ov23li43Rjen58luWgOc
  open_authoring: true
  workflow: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    preview_template: "BlogPostPreview"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
    sortable_fields: ['title', 'date']
    view_filters:
      - label: "Drafts"
        field: "draft"
        pattern: true
